src/AppBundle/Form/TagsType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class TagsType extends AbstractType {

  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder->addViewTransformer(new CallbackTransformer(
      function ($original) {
        return $original ? implode(', ', $original) : '';
      },
      function ($submitted) {
        if (!$submitted) {
          return [];
        }

        $submitted = array_map(function($tag) {
          return trim($tag);
        }, explode(',', $submitted));

        return $submitted;
      }
    ));
  }

  public function getName()
  {
    return 'tags';
  }

  public function getParent()
  {
    return TextType::class;
  }


}

src/AppBundle/Resources/views/Calendars/parts/variable_slots/modalEdit.html.twig
<div class="modal fade" tabindex="-1" role="dialog" id="modalCenter">
  <div class="modal-lg modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button id="modalClose" class="close" type="button" data-dismiss="modal" aria-label="Close">
          <svg class="icon">
            <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-close"></use>
          </svg>
        </button>
      </div>
      <div class="modal-title mx-4">
        <h5 id="modalTitle"></h5>
      </div>
      <div class="modal-body">
        <div id="modalId" class="d-none"></div>
        <div id="modalStatus" class="d-none"></div>
        <div class="row mt-3 {% if not calendar.allowOverlaps %} d-none {% endif %}">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-calendar"></use>
            </svg>
          </div>
          <div class="col-10">
            <select id="modalOpeningHour" class="selectpicker">
              {% for opening_hour in calendar.openingHours %}
                <option value="{{opening_hour.id}}">{{opening_hour.name}}</option>
              {% endfor %}
              {% if not calendar.allowOverlaps %}
                <option value="" selected>{{ "meetings.modal.all" | trans() }}</option>
              {% endif %}
            </select>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-clock"></use>
            </svg>
          </div>
          <div class="col-4">
            <input id="modalDate" type="date">
          </div>
          <div class="col-2"></div>
          <div class="col-2">
            <input type="time" id="modalStart" placeholder="{{ 'meetings.labels.select_slot_start' |  trans}}">
          </div>
          <div class="col-2">
            <input type="time" id="modalEnd"  placeholder="{{ 'meetings.labels.select_slot_end' |  trans}}">
          </div>
        </div>
        <div id="no_slots_edit_alert" class="row mt-3">
          <div class="col-1"></div>
          <div class="col-10">
            <small class="text-danger">{{ 'meetings.error.no_slots_available' | trans }}</small>
          </div>
        </div>
        <div id="edit_alert" class="row mt-3">
          <div class="col-1"></div>
          <div class="col-10">
            <small><b>{{ "meetings.modal.warning" | trans }}</b>: {{ "meetings.modal.notification_alert_confirm" | trans }}</small>
          </div>
        </div>
        <br>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-note"></use>
            </svg>
          </div>
          <div class="col-10">
            <textarea style="border: none" id="modalDescription" ></textarea>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-link"></use>
            </svg>
          </div>
          <div class="col-10">
            <input type="url" id="modalVideoconferenceLink" placeholder="{{ "meetings.labels.videoconference_link" | trans() }}">
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-telephone"></use>
            </svg>
          </div>
          <div class="col-6">
            <input type="tel" id="modalPhone" class="col-10" placeholder="{{ "meetings.labels.phone_number" | trans() }}">
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-mail"></use>
            </svg>
          </div>
          <div class="col-6">
            <input type="email" id="modalEmail" class="col-10" placeholder="{{ "meetings.labels.email" | trans() }}">
          </div>
        </div>
        <div id="modalReschedule" class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-warning-circle"></use>
            </svg>
          </div>
          <div class="col-10" id="modalRescheduleText"></div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-comment"></use>
            </svg>
          </div>
          <div class="col-10">
            <p class="mb-3 small">{{ 'meetings.modal.motivation_outcome_helper' | trans }}</p>
            <textarea style="border: none" id="modalMotivationOutcome" ></textarea>
          </div>
        </div>
        <div class="row mt-4">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-tool"></use>
            </svg>
          </div>
          <div class="col-10">
            <p id="modalStatusHelper" class="mb-3 small">{{ 'meetings.modal.status_change_helper' | trans }}</p>
            <button id="modalApprove" data-url='{{ path("meetings_api_patch", {'id': 'meeting_id'}) }}'
                    class="btn btn-success btn-sm mr-3 modal-edit" type="button" data-status="1"
                    data-confirm="{{ 'meetings.modal.confirm_edit.status_1' | trans}}">
            {{ "meetings.modal.confirm" | trans() }} <svg class="icon icon-sm icon-white"><use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-check"></use></svg>
            </button>
            <button id="modalRefuse" data-url='{{ path("meetings_api_patch", {'id': 'meeting_id'}) }}'
                    class="btn btn-danger btn-sm mr-3 modal-edit" type="button" data-status="2"
                    data-confirm="{{ 'meetings.modal.confirm_edit.status_2' | trans}}">
              {{ "meetings.modal.refuse" | trans() }} <svg class="icon icon-sm icon-white"><use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-close"></use></svg>
            </button>
            <button id="modalComplete" data-url='{{ path("meetings_api_patch", {'id': 'meeting_id'}) }}'
                    class="btn btn-success btn-sm mr-3 modal-edit" type="button" data-status="4"
                    data-confirm="{{ 'meetings.modal.confirm_edit.status_4' | trans}}">
              {{ "meetings.modal.done" | trans() }} <svg class="icon icon-sm icon-white"><use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-check"></use></svg>
            </button>
            <button id="modalMissed" data-url='{{ path("meetings_api_patch", {'id': 'meeting_id'}) }}'
                    class="btn btn-danger btn-sm mr-3 modal-edit" type="button" data-status="3"
                    data-confirm="{{ 'meetings.modal.confirm_edit.status_3' | trans}}">
              {{ "meetings.modal.absent" | trans() }} <svg class="icon icon-sm icon-white"><use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-close"></use></svg>
            </button>
            <button id="modalCancel" data-url='{{ path("meetings_api_patch", {'id': 'meeting_id'}) }}'
                    class="btn btn-warning btn-sm mr-3 modal-edit" type="button" data-status="5"
                    data-confirm="{{ 'meetings.modal.confirm_edit.status_5' | trans}}">
              {{ "meetings.modal.cancel" | trans() }} <svg class="icon icon-sm icon-white"><use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-delete"></use></svg>
            </button>
          </div>
        </div>
      </div>

      <div class="modal-footer my-3 d-flex justify-content-between" >
        <p id="modalError" class="text-danger"></p>
        <button id="modalSave" data-url='{{ path("meetings_api_patch", {'id': 'meeting_id'}) }}'
                class="btn btn-primary btn-sm modal-edit" type="button"
                data-confirm="{{ 'meetings.modal.confirm_edit.save' | trans}}">{{ "meetings.modal.save" | trans }}</button>
      </div>
    </div>
  </div>
</div>

src/AppBundle/Resources/views/Calendars/parts/variable_slots/modalNew.html.twig
<div class="modal fade" tabindex="-1" role="dialog" id="modalNew">
  <div class="modal-lg modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button id="modalClose" class="close" type="button" data-dismiss="modal" aria-label="Close">
          <svg class="icon">
            <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-close"></use>
          </svg>
        </button>
      </div>
      <div class="modal-title mx-4">
        <input id="modalNewName" type="text" placeholder="{{ 'meetings.labels.complete_name' | trans }}">
      </div>
      <div class="modal-body">
        <div id="modalId" class="d-none"></div>
        <div class="d-none" id="modalNewStatus"></div>
        <div class="row mt-3 {% if not calendar.allowOverlaps %} d-none {% endif %}">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-calendar"></use>
            </svg>
          </div>
          <div class="col-10">
            <select id="modalNewOpeningHour" class="selectpicker">
              {% for opening_hour in calendar.openingHours %}
                <option value="{{opening_hour.id}}">{{opening_hour.name}}</option>
              {% endfor %}
              {% if not calendar.allowOverlaps %}
                <option value="" selected>{{ "meetings.modal.all" | trans() }}</option>
              {% endif %}
            </select>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-clock"></use>
            </svg>
          </div>
          <div class="col-4">
            <input id="modalNewDate" type="date">
          </div>
          <div class="col-2"></div>
          <div class="col-2">
            <input type="time" id="modalNewStart" placeholder="{{ 'meetings.labels.select_slot_start' |  trans}}">
          </div>
          <div class="col-2">
            <input type="time" id="modalNewEnd"  placeholder="{{ 'meetings.labels.select_slot_end' |  trans}}">
          </div>
        </div>
        <div id="no_slots_new_alert" class="row mt-3">
          <div class="col-1"></div>
          <div class="col-10">
            <small class="text-danger">{{ 'meetings.error.no_slots_available' | trans }}</small>
          </div>
        </div>
        <br>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-note"></use>
            </svg>
          </div>
          <div class="col-10">
            <textarea style="border: none" id="modalNewDescription" placeholder="{{ 'meetings.labels.backoffice_user_message' | trans }}"></textarea>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-link"></use>
            </svg>
          </div>
          <div class="col-10">
            <input type="url" id="modalNewVideoconferenceLink" placeholder="{{ 'meetings.labels.videoconference_link' | trans }}">
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-user"></use>
            </svg>
          </div>
          <div class="col-6">
            <input type="text" id="modalNewFiscalCode" class="col-10" placeholder="{{ 'meetings.labels.fiscal_code' | trans }}">
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-telephone"></use>
            </svg>
          </div>
          <div class="col-6">
            <input type="text" id="modalNewPhone" class="col-10" placeholder="{{ 'meetings.labels.phone_number' | trans }}">
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-mail"></use>
            </svg>
          </div>
          <div class="col-6">
            <input type="email" id="modalNewEmail" class="col-10" placeholder="{{ 'meetings.labels.email' | trans }}">
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-1">
            <svg class="icon">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-comment"></use>
            </svg>
          </div>
          <div class="col-10">
            <p class="mb-3 small">{{ 'meetings.modal.motivation_outcome_helper' | trans }}</p>
            <textarea class="border-0" id="modalNewMotivationOutcome" ></textarea>
          </div>
        </div>
      </div>
      <div class="modal-footer my-3 d-flex justify-content-between" >
        <p id="modalNewError" class="text-danger"></p>
        <button id="modalCreate" class="btn btn-primary btn-sm modal-create" data-url='{{ path("meetings_api_post") }}' type="button" data-calendar="{{ calendar.id }}">{{ "meetings.modal.create" | trans }}</button>
      </div>
    </div>
  </div>x
</div>